---
title: |
   | Sesión 2: 
   | Tipos de Variables  
author: 
  - name: Alan R. Vázquez
    email: alanrvazquez@tec.mx
    affiliations:
      - name: Tecnológico de Monterrey
format: revealjs
editor: visual
slide-number: True
logo: IN2039_logo.png
css: style.css
---

## Introducción

Before making an exploratory plot, or any plot for that matter, it’s a good idea to examine the feature (or features) and decide on its *feature type*. (Sometimes we refer to a feature as a *variable* and its type as *variable type*.)

## Tipos de Datos

Existen dos tipos principales de datos:

-   Datos numéricos

-   Datos categóricos: los cuales pueden ser nominales o ordinales.

## Datos categóricos

When sample items are placed into categories and category names are assigned to the sample items, the data are **categorical** or **qualitative**.

-   Hair color.

-   Country of origin.

-   Zip code.

***Nominal***

:   A feature that represents “named” categories, where the categories do not have a natural ordering, is called nominal. Examples include political party affiliation (Democrat, Republican, Green, Other); dog type (herding, hound, non-sporting, sporting, terrier, toy, working); and computer operating system (Windows, macOS, Linux).

***Ordinal***

:   Measurements that represent ordered categories are called ordinal. Examples of ordinal features are t-shirt size (small, medium, large); Likert-scale response (disagree, neutral, agree); and level of education (high school, college, graduate school).

::: notes
It is important to note that with an ordinal feature, the difference between, say, small and medium need not be the same as the difference between medium and large. Also, the differences between consecutive categories may not even be quantifiable. Think of the number of stars in a restaurant review and what one star means in comparison to two stars.
:::

## Datos númericos

When a numerical quantity designating how much or how many is assigned to each item in the sample, the resulting set of values is **numerical** or **quantitative**. Data that represent numeric measurements or quantities are called quantitative.

-   Height (in centimeters).

-   Weight (in kilograms).

-   Age (in years).

Quantitative features can be further divided into *discrete*, meaning that only a few values of the feature are possible, and *continuous*, meaning that the quantity could in principle be measured to arbitrary precision.

## Note that...

A feature stored as an integer can represent nominal data, strings can be quantitative (like `"$100.00"`), and, in practice, boolean values often represent nominal features that have only two possible values.

# Actividad

# Conclusiones

## La importancia de los typos de variables

Feature types guide us in our data analysis.

They help specify the operations, visualizations, and models we can meaningfully apply to the data.

Whether the variable(s) are quantitative or qualitative generally determines the set of viable plots to make, although there are exceptions.

| Tipo         | Número | Gráfica                                                                                         |
|:-------------|:-------|:------------------------------------------------------------------------------------------------|
| Quantitativa | 1      | Rug plot, histogram, density curve, box plot, violin plot                                       |
| Categórica   | 1      | Bar plot, dot plot, line plot, pie chart                                                        |
| Quantitativa | 2      | Scatter plot, smooth curve, contour plot, heat map, quantile quantile plot                      |
| Categórica   | 2      | Side-by-side bar plots, mosaic plot, overlaid lines                                             |
| Mixta        | 2      | Overlaid density curves, side-by-side box plots, overlaid smooth curves, quantile quantile plot |
